service: sls-ci

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

package:
  exclude:
    - .circleci
    - .gitignore
    - .nvmrc
    - README.md
    - "*.spec.js"

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get

plugins:
  - serverless-stack-output

custom:
  output:
    file: ./serverless-info.json